### ISSUE TITLE
[Bug] --- Notifications not loading

### ISSUE THREAD

**Issue by vivekkj123** [callmearta/clubhouse-desktop#47] opened 2021-05-31 13:25 UTC
Hi there,

  Thank you for this wonderful unofficial clubhouse client. But there is a small bug on this application. The notification section is keep loading, but doesn't show anything. I've attached the screenshot below. Expecting a quick fix.

![Screenshot showing the bug](https://user-images.githubusercontent.com/58988126/120200074-8e3da700-c241-11eb-9a94-1b99b638389a.png)
 
Message from console

![Message from console](https://user-images.githubusercontent.com/58988126/120200984-8d594500-c242-11eb-99bc-e5c68b6b67db.png)

Thanks,
Vivek K J

**Comment by subins2000** [comment] 2021-05-31 14:00
Can confirm this bug. My output :
![image](https://user-images.githubusercontent.com/2305675/120204663-afed5d00-c246-11eb-8628-84722db228a4.png)

**Comment by subins2000** [comment] 2021-05-31 14:05
Here's a small script to read the notifications from that object stored in `temp` (do this in browser console) :

```
Object.keys(temp1.notifications).forEach((k) => {
  o = temp1.notifications[k]
  if ('user_profile' in o)
    console.log(o.message + " - " + o.user_profile.name)
  else
    console.log(o.message)
})
```

**Comment by callmearta** [comment] 2021-05-31 14:41
The problem is in some notification objects which don't posses a user_id. Feel free to do a PR if you managed to fix it. I don't have time rn to do so.

**Comment by callmearta** [comment] 2021-06-01 16:02
Latest PR merged and the problem now should be gone. Closing this for now

**Closed as completed by callmearta** 2021-06-01 16:02 UTC

**Comment by stultus** [comment] 2021-06-01 22:13
I'm still getting this issue in the latest version 

![image](https://user-images.githubusercontent.com/328309/120396695-a3572a80-c354-11eb-929b-34cca0b2d3a5.png)
